# <center>Assignment 4


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Name: Votata SREY



# Part 1

**In part 1 you need to work with data from the about 120 years of Olympic history by pandas. Write code and perform computations in the cells below. There are five questions.**

Download the file `athlete_events.csv` from [here](https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results). The dataset has the following features:

- __ID__ - Unique number for each athlete
- __Name__ - Athlete's name
- __Sex__ - M or F
- __Age__ - Integer
- __Height__ - In centimeters
- __Weight__ - In kilograms
- __Team__ - Team name
- __NOC__ - National Olympic Committee 3-letter code
- __Games__ - Year and season
- __Year__ - Integer
- __Season__ - Summer or Winter
- __City__ - Host city
- __Sport__ - Sport
- __Event__ - Event
- __Medal__ - Gold, Silver, Bronze, or NA

In [3]:
import pandas as pd
import numpy as np

In [7]:
PATH = '/content/drive/MyDrive/Classroom/MIS 512 Section 1 (AY 2023-2024)/Assignment_4/athlete_events.csv'
athletes_data = pd.read_csv(PATH)
athletes_data.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

**1**. How old were the oldest male and female participants of the 2012 Olympics?

In [16]:
olympics_2012 = athletes_data[athletes_data['Year'] == 2012]
oldest_male_2012 = olympics_2012[olympics_2012['Sex'] == 'M']['Age'].max()
oldest_female_2012 = olympics_2012[olympics_2012['Sex'] == 'F']['Age'].max()

print("**"*100)
print("Oldest Atheltes Male : ", oldest_male_2012)
print("Oldest Atheltes Female : ", oldest_female_2012)
print("**"*100)

********************************************************************************************************************************************************************************************************
Oldest Atheltes Male :  71.0
Oldest Atheltes Female :  57.0
********************************************************************************************************************************************************************************************************


__2. What are the mean and standard deviation of height for male basketball players who participated in the 1992 Olympics? Round the answer to the first decimal.__

In [17]:
basketball_1992_men = athletes_data[(athletes_data['Year'] == 1992) &
                                    (athletes_data['Sex'] == 'M') &
                                    (athletes_data['Sport'] == 'Basketball')]

mean_height = basketball_1992_men['Height'].mean()
std_dev_height = basketball_1992_men['Height'].std()

mean_height_rounded = round(mean_height, 1)
std_dev_height_rounded = round(std_dev_height, 1)

print("**"*100)
print("Male Basketball Average (Height) : ", mean_height_rounded)
print("Male Basketball Standard Deviation (Height) : ", std_dev_height_rounded)
print("**"*100)

********************************************************************************************************************************************************************************************************
Male Basketball Average (Height) :  199.5
Male Basketball Standard Deviation (Height) :  9.5
********************************************************************************************************************************************************************************************************


__3. How many times did Christine Jacoba Aaftink participate in the Olympics held in different years?__

In [15]:
player_filter = 'Christine Jacoba Aaftink'
aaftink_data = athletes_data[athletes_data['Name'] == player_filter]

unique_years = aaftink_data['Year'].unique()
participation_count = len(unique_years)

print("**"*100)
print("The ", player_filter, " Have participanted in the Olympics in ", participation_count, " Times within these ", unique_years, " years")
print("**"*100)

********************************************************************************************************************************************************************************************************
The  Christine Jacoba Aaftink  Have participanted in the Olympics in  3  Times within these  [1988 1992 1994]  years
********************************************************************************************************************************************************************************************************


__4. Is it true that China won fewer medals than Russia at the 2012 Olympics? Do not consider NaN values in Medal column.__

In [19]:
china_medals_2012 = olympics_2012[(olympics_2012['Team'] == 'China') & (olympics_2012['Medal'].notna())]
russia_medals_2012 = olympics_2012[(olympics_2012['Team'].str.contains('Russia')) & (olympics_2012['Medal'].notna())]

china_medal_count = china_medals_2012['Medal'].count()
russia_medal_count = russia_medals_2012['Medal'].count()

if china_medal_count < russia_medal_count:
  print("**"*100)
  print("Yes it is true, the china has won fewer medals than Russia")
  print("**"*100)
else:
  print("**"*100)
  print("Yes it is NOT True")
  print("**"*100)

********************************************************************************************************************************************************************************************************
Yes it is true, the china has won fewer medals than Russia
********************************************************************************************************************************************************************************************************


__5. What is the absolute difference between the number of unique sports at the 1986 Olympics and 2016 Olympics?__

In [25]:
# based on the dataset, there is no 1986 Olympic, professor. So I will analyze on the 1896 instead of that.

unique_olympic_years = athletes_data['Year'].unique()
unique_olympic_years.sort()
print( "These are the year of Olympics helds, there is no 1986. \n\n" , unique_olympic_years)
print("\n\n")

olympics_1896_sports = athletes_data[athletes_data['Year'] == 1896]['Sport'].unique()
olympics_2016_sports = athletes_data[athletes_data['Year'] == 2016]['Sport'].unique()
unique_sports_1896 = len(olympics_1896_sports)
unique_sports_2016 = len(olympics_2016_sports)

absolute_difference_sports = abs(unique_sports_1896 - unique_sports_2016)
unique_sports_1896, unique_sports_2016, absolute_difference_sports

print("**"*100)
print("So these are the absolute different between number of unique sports at the 1896 and 2016 : \n\n")
print("##"*30)
print("The unique sports in 1896: ", unique_sports_1896)
print("The unique sports in 2016: ", unique_sports_2016)
print("The absolute different between number of unique sports at the 1896 and 2016: ", absolute_difference_sports)
print("**"*100)

These are the year of Olympics helds, there is no 1986. 

 [1896 1900 1904 1906 1908 1912 1920 1924 1928 1932 1936 1948 1952 1956
 1960 1964 1968 1972 1976 1980 1984 1988 1992 1994 1996 1998 2000 2002
 2004 2006 2008 2010 2012 2014 2016]



********************************************************************************************************************************************************************************************************
So these are the absolute different between number of unique sports at the 1896 and 2016 : 


############################################################
The unique sports in 1896:  9
The unique sports in 2016:  34
The absolute different between number of unique sports at the 1896 and 2016:  25
********************************************************************************************************************************************************************************************************


# Part 2

**In part 2 you need to work with numpy library. Write code and perform computations in the cells below. There are five questions.**

In [26]:
import numpy as np

__6. Create a 5x5 matrix with row values ranging from 0 to 4__

In [27]:
matrix = np.tile(np.arange(0, 5), (5, 1))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

__7. Create a random vector of size 10 and sort it__

In [28]:
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)

sorted_vector

array([0.2322058 , 0.23829238, 0.3601967 , 0.50220494, 0.54339725,
       0.78644502, 0.82439298, 0.83278905, 0.8398064 , 0.9780468 ])

__8. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area__

In [29]:
Z = np.zeros((10,10), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

__9. Consider two random array A and B, check if they are equal__

In [32]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

arrays_equal = np.array_equal(A, B)
if arrays_equal == True:
  print("**"*100)
  print("Yes array A and B are equal")
  print("**"*100)
else:
  print("**"*100)
  print("No, array A and B are NOT equal")
  print("**"*100)

********************************************************************************************************************************************************************************************************
No, array A and B are NOT equal
********************************************************************************************************************************************************************************************************


__10. Create a random matrix and swap two rows of an array?__

In [35]:
random_matrix = np.random.rand(4, 4)

print("**"*100)
print("Original Array \n")
print(random_matrix)
print("**"*100)

print("\n\n Swaping .... \n\n")
random_matrix[[1, 3]] = random_matrix[[3, 1]]


print("**"*100)
print("Swapping two rows of an array of 1 and 3\n")
print(random_matrix)
print("**"*100)

********************************************************************************************************************************************************************************************************
Original Array 

[[0.41466423 0.19847106 0.56417308 0.81249975]
 [0.49807706 0.57063108 0.88209964 0.36145535]
 [0.72448963 0.66475538 0.50405286 0.01599341]
 [0.48509291 0.45376911 0.33714221 0.97491198]]
********************************************************************************************************************************************************************************************************


 Swaping .... 


********************************************************************************************************************************************************************************************************
Swapping two rows of an array of 1 and 3

[[0.41466423 0.19847106 0.56417308 0.81249975]
 [0.48509291 0.45376911 0.33714221 0.97491198]
 [0.72448963 0.66475538 0.50405286 0